- src/HTTPRequest.php
> Fix error with PHP 7.2

- README.md
Save from trying to figure out the syntax accepted by the engine.
> Add filter example

- README.md
Remove bad practice as suggested on https://github.com/meilisearch/meilisearch-php/pull/20#discussion_r412413307
> Update filters to remove bad practice

- .code-samples.meilisearch.yaml
- .editorconfig
> Add getting started code samples

- .code-samples.meilisearch.yaml
> add code-samples

- .code-samples.meilisearch.yaml
- README.md
Introduction sentence based on https://github.com/GitLabPHP/Client#installation
> Update docs for HTTP Client compatibilities

- README.md
- src/Client.php
- src/Http/Client.php
> Remove the ability to replace Response and Request Factories

- .code-samples.meilisearch.yaml
- src/Client.php
- src/Endpoints/Delegates/HandlesDumps.php
- src/Endpoints/Dumps.php
- tests/Endpoints/DumpTest.php
add support of [dumps](https://docs.meilisearch.com/references/dump.html#create-a-dump)
> Add dumps methods

- README.md
Replace movies with book in README
> Replace movies with book in README

- src/Exceptions/ApiException.php
- tests/Exceptions/ApiExceptionTest.php
Discussed here https://github.com/meilisearch/meilisearch-php/issues/50
> Add more details MeiliSearch\Exceptions\ApiException

- .github/workflows/tests.yml
Closes #163 
This PR enables the test for [kriswallsmith/Buzz](https://github.com/kriswallsmith/Buzz) and [php-http/curl-client](https://github.com/php-http/curl-client/).
> Run test for http clients

- .github/workflows/tests.yml
- .php-cs-fixer.dist.php
- composer.json
- phpstan.neon
- src/Contracts/Endpoint.php
- src/Delegates/HandlesIndex.php
- src/Endpoints/Indexes.php
- src/Http/Client.php
- src/Search/SearchResult.php
- tests/Endpoints/ClientTest.php
- tests/Endpoints/DocumentsTest.php
- tests/Endpoints/SearchTest.php
- tests/Search/SearchResultTest.php
This PR introduces phpstan for better type checks - for the `src/` and for the `test/` files.
> Better type checking with phpstan

- src/Exceptions/ApiException.php
- tests/Exceptions/ApiExceptionTest.php
> Fix logging for ApiException

- .code-samples.meilisearch.yaml
Error in `update_settings_1` and `update_synonyms_1`
> Fix typo in code sample

- src/Endpoints/Indexes.php
- tests/Endpoints/ClientTest.php
- tests/Endpoints/IndexTest.php
- tests/Endpoints/SearchTest.php
- tests/Settings/RankingRulesTest.php
- tests/Settings/SettingsTest.php
- Adapts tests according to v0.21.0 breaking changes
- Rename `buildDate` into `commitDate`
- Rename `fieldsDistribution` into `fieldDiestribution`
- Update `rankingRules`
> Fix tests according to v0.21.0

- src/Search/SearchResult.php
- tests/Endpoints/SearchTest.php
- tests/Search/SearchResultTest.php
Add missing tests according to new features
- Add phrase search tests
- Add search test including filter with number
> Add missing tests

- .code-samples.meilisearch.yaml
> Fix bad syntax in code sample

- src/Delegates/HandlesIndex.php
- tests/Endpoints/ClientTest.php
> Add deleteIndexIfExists method

- README.md
Fixes #250
Thank you so much for contributing to MeiliSearch!
Simple typo fix in the readme.
> Documentation typo fix

- src/Delegates/HandlesIndex.php
- tests/Endpoints/ClientTest.php
Removing `getOrCreateIndex` method
> Remove `getOrCreateIndex` method

- .code-samples.meilisearch.yaml
Add new code samples due to changes related to v0.25.0
> Adding new code samples

- src/MeiliSearch.php
Bump version to 0.21.0 for next release.
> Bump version for next release v0.21.0

- src/Client.php
- src/Contracts/Endpoint.php
- src/Delegates/HandlesSystem.php
- src/Endpoints/Delegates/HandlesTasks.php
- src/Endpoints/Indexes.php
- src/Endpoints/Tasks.php
- src/Exceptions/ApiException.php
- src/Http/Client.php
- src/Http/Serialize/Json.php
- src/Http/Serialize/SerializerInterface.php
- src/Search/SearchResult.php
- tests/Endpoints/IndexTest.php
- tests/Endpoints/SearchTest.php
- tests/Endpoints/TasksTest.php
- tests/Search/SearchResultTest.php
- tests/Settings/DistinctAttributeTest.php
- tests/Settings/RankingRulesTest.php
- tests/Settings/StopWordsTest.php
- tests/Settings/SynonymsTest.php
- tests/TestCase.php
This adds PHP 7.4 typed properties and some types to methods.
> Add typed properties and more typed parameters to methods

- composer.json
This updates to the current stable PHPStan version
> Update PHPstan to stable version 1

- phpstan.neon
- src/Contracts/Http.php
- src/Delegates/HandlesIndex.php
- src/Delegates/HandlesSystem.php
- src/Endpoints/Delegates/HandlesDocuments.php
- src/Endpoints/Delegates/HandlesDumps.php
- src/Endpoints/Delegates/HandlesKeys.php
- src/Endpoints/Delegates/HandlesSettings.php
- src/Endpoints/Delegates/HandlesTasks.php
- src/Exceptions/ApiException.php
- src/Http/Client.php
- tests/Endpoints/ClientTest.php
- tests/Endpoints/DocumentsTest.php
- tests/Endpoints/IndexTest.php
- tests/Endpoints/KeysAndPermissionsTest.php
- tests/Endpoints/TasksTest.php
- tests/Search/SearchResultTest.php
- tests/Settings/DisplayedAttributesTest.php
- tests/Settings/FilterableAttributesTest.php
- tests/Settings/RankingRulesTest.php
- tests/Settings/SearchableAttributesTest.php
- tests/Settings/SortableAttributesTest.php
- tests/Settings/StopWordsTest.php
- tests/Settings/SynonymsTest.php
- tests/TestCase.php
Fixes #182
I split up each level into a seperate commit to follow easier.
I didn't increase to level > 5 because we would need to add specific typed docblocks to each method that returns an array. It could be handy in the future, but I think there are better ways to solve that.
This is in Draft mode because it depends on PR #286
> Improve phpstan level

- .code-samples.meilisearch.yaml
Missing comma in array definition
Fixes an incorrect code sample
> Update code sample to fix incorrect syntax

- .code-samples.meilisearch.yaml
Following [this issue](https://github.com/meilisearch/integration-guides/issues/190)
Updating one and addition of new samples.
> Updating code-sample for v0.27.0

- src/Endpoints/Indexes.php
- tests/Endpoints/ClientTest.php
- tests/Endpoints/IndexTest.php
- Use results attribute to retrieve the list of indexes
> Apply indexes changes v1

- .code-samples.meilisearch.yaml
- docker-compose.yml
- src/Delegates/HandlesSystem.php
- src/Endpoints/Indexes.php
- src/Endpoints/Keys.php
- tests/Endpoints/ClientTest.php
- tests/Endpoints/DumpTest.php
- tests/Endpoints/KeysAndPermissionsTest.php
- tests/Endpoints/TenantTokenTest.php
- tests/TestCase.php
@alallema suggested some changes in the last pre-release PR, this PR summarizes all of them.
> Code review changes

- src/Contracts/TasksQuery.php
- src/Contracts/TasksResults.php
- src/Endpoints/Delegates/HandlesTasks.php
- src/Endpoints/Indexes.php
- src/Endpoints/Tasks.php
- tests/Contracts/TasksQueryTest.php
- tests/Endpoints/IndexTest.php
- tests/Endpoints/TasksTest.php
- Create `TasksQuery` and `TasksResults` to have pagination and filtering in the tasks endpoints.
- Apply them to the tasks endpoints
> Tasks changes v2

- src/Contracts/IndexesResults.php
> Fix bad typehint

- src/Endpoints/Indexes.php
Fixes #359
- [ x ] Does this PR fix an existing issue?
- [ x ] Have you made sure that the title is accurate and descriptive of the changes?
> Pass $options to http request

- src/Endpoints/Delegates/HandlesSettings.php
- tests/Endpoints/IndexTest.php
Fixes #355 and #354
https://github.com/meilisearch/meilisearch-php/issues/355
https://github.com/meilisearch/meilisearch-php/issues/354
> Methods to get/update/delete faceting and pagination index settings

- src/Client.php
- src/Http/Client.php
- tests/Http/ClientTest.php
Related to https://github.com/meilisearch/integration-guides/issues/150
> Add the ability to provide extra custom user-agents

- src/Search/SearchResult.php
- tests/Endpoints/SearchTest.php
Ensure the support of `matchingStrategy` query parameter.
> Add tests to matchingStrategy

- src/Endpoints/Delegates/HandlesDocuments.php
Fixes #372 
- Sending correct batch document instead of all documents in foreach loop
> This will fix docs in batches sending same chunk

- src/Client.php
Add strongly typed property.
Fixes #385
- Applies suggestion of #385
> Enforce strong type property - related with #385

- docker-compose.yml
- phpunit.xml.dist
- tests/TestCase.php
Fixes #390 
- It replace MEILISEARCH_HOST by MEILISEARCH_URL in the docker config
> Replace MEILISEARCH_HOST by MEILISEARCH_URL

- .github/workflows/docs.yml
Fixes #325 
- Add [phpDocumentor](https://www.phpdoc.org/) generation to the the github actions.
> Add PHP hosted documentation

- .github/workflows/docs.yml
Relates to #325 #393
- The first implementation had all the classes that were related to testing, so this time I added a new configuration to remove it from the final build.
> Remove test path from phpDocumentor run

- .code-samples.meilisearch.yaml
Fixes #403
- Adds two new code samples requested
#hacktoberfest
> Added two new code-sample requested

- src/MeiliSearch.php
This release will contain all the changes related to Hacktoberfest. Thanks for all the contributions! ❤️
> Update version for the next release (v0.25.1)

- src/MeiliSearch.php
This version makes this package compatible with Meilisearch v0.30.0 :tada:
Check out the changelog of [Meilisearch v0.30.0](https://github.com/meilisearch/meilisearch/releases/tag/v0.30.0) for more information on the changes.
<details>
<summary>Add support to finite pagination (#418) @brunoocasali </summary>
Now you can call: 
- `$client.search('batman', [ 'page' => 1, 'hitsPerPage' => 10 ])`
- `$client.search('batman', [ 'hitsPerPage' => 10 ])`
- `$client.search('batman', [ 'page' => 4 ])`
`results = $client.search('batman', [ 'page' => 4 ])`
And get a limited pagination with a fixed number of total hits in the results object `results['totalHits']`.
You can still use the `offset/limit` by calling `$client.search('batman', [ 'limit' => 4, 'offset' => 10 ])`
`SearchResult#hitsCount` can …
> Update version for the next release (v0.26.0)

- src/Meilisearch.php
- Move from `MeiliSearch` to `Meilisearch` everywhere.
> Update the version for the next release (v0.26.1)

- .code-samples.meilisearch.yaml
Just code-samples improvements suggested by @bidoubiwa in the private call.
> Code samples improvements

- src/Client.php
- src/Contracts/CancelTasksQuery.php
- src/Contracts/DeleteTasksQuery.php
- src/Contracts/TasksQuery.php
- src/Endpoints/Delegates/HandlesIndex.php
- src/Endpoints/Delegates/HandlesSystem.php
- src/Endpoints/Delegates/TasksQueryTrait.php
Move traits to a commonplace `src/Endpoints/Delegates`.
> Move traits to src/Endpoints/Delegates

- .code-samples.meilisearch.yaml
Based on the comments from the #435 PR this PR introduces the following:
- A common way of `->search()` requests declaration.
- Missing semicolons in multiple calls.
> Standardize code-samples

- tests/Contracts/CancelTasksQueryTest.php
- tests/Contracts/DeleteTasksQueryTest.php
- tests/Contracts/DocumentsQueryTest.php
- tests/Contracts/IndexesQueryTest.php
- tests/Contracts/KeysQueryTest.php
- tests/Contracts/TasksQueryTest.php
- tests/Endpoints/TasksTest.php
Fixes #449 
- Switch the passed assertion arguments in several test classes
> Tests: switch expected and actual values for assertions

- .github/workflows/tests.yml
- src/Contracts/Data.php
- src/Contracts/Endpoint.php
- src/Endpoints/Delegates/HandlesDocuments.php
- src/Exceptions/ApiException.php
- src/Exceptions/InvalidResponseBodyException.php
- src/Exceptions/JsonDecodingException.php
- src/Exceptions/JsonEncodingException.php
- src/Exceptions/TimeOutException.php
- src/Http/Client.php
- src/Http/Serialize/Json.php
> Fix composer:lint errors

- README.md
This updates the docs URL in the README from `https://php-sdk-docs.meilisearch.com` to `https://php-sdk.meilisearch.com`
> Update SDK docs link in README.md

- src/Contracts/Index/Faceting.php
- src/Contracts/Index/Settings.php
- src/Endpoints/Delegates/HandlesSettings.php
- tests/Settings/FacetingAttributesTest.php
Add faceting settings type and support to send the new configuration `sortFacetValuesBy`.
> Add faceting settings

- src/Contracts/TasksResults.php
- tests/Endpoints/TasksTest.php
Add `total` to `TasksResults`.
> Add getTotal() in the TasksResults type

- .code-samples.meilisearch.yaml
Adds code-samples for v1.3 https://github.com/meilisearch/integration-guides/issues/282
> Code samples for v1.3

- .github/workflows/tests.yml
Fixes https://github.com/meilisearch/meilisearch-symfony/pull/286#discussion_r1297873653
- ...
> Let GitHub Actions to setup meilisearch docker service

- src/Endpoints/Delegates/HandlesSettings.php
- tests/Settings/NonSeparatorTokensTest.php
- tests/Settings/SeparatorTokensTest.php
Fixes #570 
- Add separator tokens settings
- Create tests
> [v1.4] Add separator tokens and non-separator tokens setting

- .code-samples.meilisearch.yaml
Related to https://github.com/meilisearch/documentation/issues/2556
> Add code samples for v1.4.0

- .github/workflows/update-version.yml
- CONTRIBUTING.md
I cannot test it directly before merging it sorry -> this is how `workflow_dispatch` works with GitHub Actions
@mmachatschek and @norkunas I pinged both of you to be aware of the tool, but I only need one review 😊
> Add CI to update library version

- .github/workflows/update-version.yml
Following this test: https://github.com/meilisearch/meilisearch-php/pull/590 😅
> Fix automation to update version

- src/Endpoints/Delegates/HandlesTasks.php
- src/Endpoints/Tasks.php
Fixes #<issue_number>
- Adds `@throws` php docs
> Declare `@throws` in HandlesTasks delegate

- .github/workflows/docs.yml
Fixes #634
- Fixes build error
> Fix Documentation CI

- src/Search/SearchResult.php
- tests/Endpoints/SearchTest.php
- tests/Settings/EmbeddersTest.php
Fixes https://github.com/meilisearch/meilisearch-php/issues/632
- Ensure the distribution will work in the embedders
- Add a new `getSemanticHitCount` value in the `SearchResult` instance
> Add Hybrid search changes for v1.8

- src/Contracts/SearchQuery.php
- tests/Endpoints/SearchTest.php
Fixes #641 
- Add ranking score threshold
> Add ranking score threshold

- src/Contracts/SearchQuery.php
- tests/Endpoints/MultiSearchTest.php
- tests/Endpoints/SearchTest.php
Fixes #646
- Add distinct attribute at search
> Add distinct attribute at search

- .github/scripts/get-latest-meilisearch-rc.sh
- .github/workflows/meilisearch-beta-tests.yml
- .github/workflows/pre-release-tests.yml
> Sync CI test workflows

- phpunit.xml.dist
- tests/Settings/EmbeddersTest.php
> Update phpunit migration & embedders test flaky test

- .code-samples.meilisearch.yaml
> Fix similar docs code sample

- .github/workflows/meilisearch-beta-tests.yml
- .github/workflows/pre-release-tests.yml
- .github/workflows/tests.yml
- bors.toml
> Update CI to run with PHP 8.4

- .code-samples.meilisearch.yaml
Add code samples for v1.12 features
⚠️  I initially created the PR to merge into `main` instead of `bump-*`, tests may fail because of this.
> Add 1.12 code samples

- src/Contracts/DocumentsQuery.php
- src/Contracts/FacetSearchQuery.php
- src/Endpoints/Delegates/HandlesSettings.php
- tests/Contracts/DocumentsQueryTest.php
- tests/Contracts/FacetSearchQueryTest.php
- tests/Endpoints/BatchesTest.php
- tests/Endpoints/DocumentsTest.php
- tests/Settings/EmbeddersTest.php
- tests/Settings/FilterableAttributesTest.php
This PR implements v1.14.0 changes as described in https://github.com/meilisearch/integration-guides/issues/315
In particular:
- Add new `composite` source for embedders (https://github.com/meilisearch/meilisearch/issues/5343)
- Add new `pooling` parameter for `huggingFace` embedders (same issue)
- Update settings API to handle the new granular `filterableAttributes` syntax (https://github.com/meilisearch/meilisearch/issues/5163)
- Update getDocuments to allow fetching documents by ID (https://github.com/meilisearch/meilisearch/issues/5345)
- Add `progressTrace` to batches `stats` (https://github.com/meilisearch/meilisearch/issues/5359)
- Update search to handle new `exhaustiveFacetCount` parameter (https://github.com/meilisearch/meilisearch/issues/5403)
Please check if your PR fulfills …
> Implement v1.14.0 features

- .code-samples.meilisearch.yaml
- src/Endpoints/Delegates/HandlesSettings.php
- tests/Settings/FilterableAttributesTest.php
- Update filterable attribute tests to use mixed (old + new) syntax for filterable attributes
- Update the `getFilterableAttributes` and `setFilterableAttributes` docs accordingly
- Update code samples accordingly
> Add mixed filterable attributes example and update types
