README.md
src/Index.php
src/MeiliSearch.php
tests/DocumentsTest.php
tests/IndexTest.php
tests/SearchTest.php
tests/Settings/AcceptNewFieldsTest.php
tests/Settings/DisplayedAttributesTest.php
tests/Settings/DistinctAttributeTest.php
tests/Settings/RankingRulesTest.php
tests/Settings/SearchableAttributesTest.php
tests/Settings/SettingsTest.php
tests/Settings/StopWordsTest.php
tests/Settings/SynonymsTest.php
tests/UpdatesTest.php

Related to [this issue](https://github.com/meilisearch/integrations-guides/issues/1).
- Rename `waitForUpdateStatus` into `waitForPendingUpdate`
- Add tests for this method
Bonus:
- Prepare for the `v0.10`
- Remove `define('__ROOT__', dirname(dirname(__FILE__)));` line in tests file to avoid this warning when running tests:
```
Notice: Constant __ROOT__ already defined in /Users/curquiza/Documents/meilisearch-php/tests/Settings/DisplayedAttributesTest.php on line 6
PHP Notice:  Constant __ROOT__ already defined in /Users/curquiza/Documents/meilisearch-php/tests/Settings/RankingRulesTest.php on line 6
```

Wait for pending update method

---

composer.json
scripts/tests.sh
src/Client.php
src/Index.php
tests/ClientTest.php
tests/DocumentsTest.php
tests/Endpoints/ClientTest.php
tests/Endpoints/DocumentsTest.php
tests/Endpoints/IndexTest.php
tests/Endpoints/KeysAndPermissionsTest.php
tests/Endpoints/SearchTest.php
tests/Endpoints/UpdatesTest.php
tests/IndexTest.php
tests/KeysAndPermissionsTest.php
tests/SearchTest.php
tests/Settings/AcceptNewFieldsTest.php
tests/Settings/DisplayedAttributesTest.php
tests/Settings/DistinctAttributeTest.php
tests/Settings/RankingRulesTest.php
tests/Settings/SearchableAttributesTest.php
tests/Settings/SettingsTest.php
tests/Settings/StopWordsTest.php
tests/Settings/SynonymsTest.php
tests/TestCase.php
tests/UpdatesTest.php
tests/utils.php

Hi, This is obviously a big pull request. Please take time to review it especially because this is the test suite. But I have made changes in small chunks so that the review process will be easier. That is also the reason you can see a big commit list.
I will give you an idea about the changes I have done in this PR.
- There is a base TestCase.php class which all the test classes should extend and its a place we can have the basic bootstrapping of our test suite
- Then I have gone through each test classes and removed/replaced the static methods by making use of `constructor()` and `setup()` methods as necessary and isolated each test methods to be run independently of each other. Then made sure the entire test class passes and then the whole suite. Then move on to the next class.
- One …

Refactored test suite to make sure the tests are running isolated

---

src/Index.php
tests/Settings/AttributesForFacetingTest.php

NB: tests do not run yet because the v0.11 is not out.
If you want to run the tests with the last version of MeiliSearch, use `cargo` in the MeiliSearch repo, and go on my branch.
The tests in local:
```bash
$ sh scripts/tests.sh
Setting FDs limit to 1000
Launching tests...
PHPUnit 8.5.4 by Sebastian Bergmann and contributors.
............F..............................F..................... 65 / 87 ( 74%)
......................                                            87 / 87 (100%)
Time: 3.76 seconds, Memory: 8.00 MB
There were 2 failures:
1) Tests\Endpoints\ClientTest::testExceptionIfNoIndexWhenDeleting
Failed asserting that exception of type "MeiliSearch\Exceptions\HTTPRequestException" is thrown.
2) Tests\Endpoints\IndexTest::testExceptionIsThrownIfNoIndexWhenDeleting
Failed …
```

Add facets settings routes

---

src/Index.php
tests/Endpoints/SearchTest.php
tests/TestCase.php

<s><img width="745" alt="Capture d’écran 2020-06-04 à 20 35 23" src="https://user-images.githubusercontent.com/20380692/83797437-f0051880-a6a2-11ea-908e-9d6bdc70f09a.png">
Because of [this issue](https://github.com/meilisearch/MeiliSearch/issues/741).</s>
Issue fixed! All the tests pass!
Just found out that writing:
```php
public function search($query, array $options = [])
```
instead of
```php
public function search($query, $options = [])
```
raises this kind of beautiful error if you try to call the method this way
```php
search('prince', null);
```
```bash
TypeError: Argument 2 passed to MeiliSearch\Index::search() must be of the type array, null given, called in /Users/curquiza/Documents/meilisearch-php/tests/Endpoints/SearchTest.php on line 16
```
Very explicit for our users …

Implement faceting in search

---

README.md
src/Client.php
tests/Endpoints/ClientTest.php
tests/Endpoints/IndexTest.php
tests/Settings/DisplayedAttributesTest.php
tests/Settings/SearchableAttributesTest.php
tests/Settings/SettingsTest.php

Related to [this comment](https://github.com/meilisearch/integration-guides/issues/2#issuecomment-642012475).
Before:
```php
$client->createIndex('indexUID')
$client->createIndex(['uid' => 'indexUID', 'primaryKey' => 'book_id'])
```
After:
```php
$client->createIndex('indexUID')
$client->createIndex('indexUID', ['primaryKey' => 'book_id'])
```

Change create_index prototype

---

tests/Settings/SettingsTest.php

The tests currently fail because of [this issue](https://github.com/meilisearch/MeiliSearch/issues/798).

Update tests after MeiliSearch bump to v0.12.0

---

README.md
src/Client.php
tests/Endpoints/ClientTest.php

Implements the `getOrCreateIndex` method, as specified in [this discussion](https://github.com/meilisearch/integration-guides/issues/2)
* Add `getOrCreateIndex` method
* Add tests
* Update Readme with examples
> Related to issue #26

Add new method `getOrCreateIndex`

---

CONTRIBUTING.md

I would like to add this line in the CONTRIBUTING.md file since a contributor was lost with an error in local that he could not see on the CI. See #62.
@eskombro and @bidoubiwa I would like to add this explanation in all the other SDKs, what do you think? 🙂

Add explanation about how to fetch the MeiliSeach latest in CONTRIBUTING.md

---

src/Endpoints/Indexes.php
tests/Endpoints/SearchTest.php

Use `POST` route instead of `GET` for search method
- `attributesToHighlight`, `attributesToRetrieve` and `attributesToCrop` must always be an array (instead of a string) so it is properly deserialized by the server
- `matches` needs to be a boolean (not a string) to be properly deserialized by the server
- Tests added for [placeholder search](https://github.com/meilisearch/MeiliSearch/pull/771)
Tested against v0.13.0 release candidate 0: https://github.com/meilisearch/MeiliSearch/releases/tag/v0.13.0rc0
Closes #66

Implement POST route in search method

---

README.md
composer.json
src/Http/Client.php

As discussed in #76, instead of using `HttpClientDiscovery::find()` within the `Http\Client`, we should use `Psr18ClientDiscovery::find()`. This allows us to a variety of HTTP Clients such as:
- `kriswallsmith/buzz`
- `php-http/curl-client`
- `symfony/http-client` with `nyholm/psr7`
- `guzzle6-adapter`
- `guzzle7` with `http-interop/http-factory-guzzle`

Replace HttpClientDiscovery with Psr18ClientDiscovery

---

.code-samples.meilisearch.yaml
README.md
composer.json
tests/Endpoints/ClientTest.php

Fixes #91 
I replaced `NetworkException` by `\Exception` (in test `testBadClientUrl`) because the exception class changes depending on the client (I anticipate #92).
For example, for guzzle 7 the exception raised is `GuzzleHttp\Exception\ConnectException` and for guzzle < 7 the exception raised is `Http\Client\Exception\NetworkException`

Docs guzzle7

---

.code-samples.meilisearch.yaml

Fix 1:  `filtering_guide_4` -> Fix espace
There was a syntax problem.
https://docs.meilisearch.com/guides/advanced_guides/filtering.html#examples
Fix 2:  `settings_guide_displayed_1` -> Wrong method
Needs to use 'Displayed' instead of 'Searchable' Attributes
https://docs.meilisearch.com/guides/advanced_guides/settings.html#example-7

Fix code samples errors

---

.github/workflows/tests.yml

Fixes #92 
And adds:
```yml
- name: Install PHP
uses: shivammathur/setup-php@v2
with:
php-version: ${{ matrix.php-versions }}
```
in the CI, because the only PHP version tested was PHP 7.4 before this fix despite the `matrix`.
⚠️ Should be merged after #94

Test compatible clients in CI

---

src/Http/Client.php

sometimes the body response is `null` and even if `null` looks like authorized it will throw this error:
```bash
Error : Wrong parameters for MeiliSearch\Exceptions\HTTPRequestException([string $message [, long $code [, Throwable $previous = NULL]]])
.../meilisearch-php/src/Exceptions/HTTPRequestException.php:21
```
by returning `$response->getReasonPhrase()` the error should not happen again
```php
....
* @return string Reason phrase; must return an empty string if none present.
*/
public function getReasonPhrase();
```
In my test case:
using a wrong url -> http://localhost instead of http://localhost:7700 will return
```bash
MeiliSearch\Exceptions\HTTPRequestException : Not Found
.../meilisearch/meilisearch-php/src/Http/Client.php:183
```
I guess this will also solve …

fix HTTPRequestException when body is null

---

src/Delegates/HandlesIndex.php
src/Endpoints/Indexes.php

Fixes #79
As per the discussion in the related issue, the method `HandlesIndex::deleteIndex` returns void but should return an array given that Meilisearch delete api could return an array in the future.
Added few lines to always return the array from the Meilisearch delete response, if null, returns an empty array

Update delete index to always return an array

---

README.md
tests/Endpoints/SearchTest.php

This PR:
- will fail in this CI until the MeiliSearch's release v0.15.0 is out
- should work locally with the [prerelease v0.15.0rc0](https://github.com/meilisearch/MeiliSearch/releases/tag/v0.15.0rc0)
⚠️ This PR should not be merged until the MeiliSearch's release v0.15.0 is out.

Changes about the MeiliSearch's next release (v0.15.0)

---

.code-samples.meilisearch.yaml

The PHP SDK did not contain any method for the `PUT health/` route, so, only the code-samples have to be removed.

Remove update_health from code-samples

---

.code-samples.meilisearch.yaml
README.md
tests/Endpoints/DumpTest.php

Related to this issue: https://github.com/meilisearch/integration-guides/issues/52
This PR:
- gathers the changes related to the next release of MeiliSearch (v0.16.0) so that this package is ready when the official release is out.
- should pass the tests against the [latest prerelease of MeiliSearch](https://github.com/meilisearch/MeiliSearch/releases). This should be tested locally.
- might eventually fail until the MeiliSearch v0.16.0 is out.
⚠️ This PR should NOT be merged until the MeiliSearch's next release (v0.16.0) is out.

Changes about the MeiliSearch's next release (v0.16.0)

---

.github/release-draft-template.yml
.github/workflows/pre-release-tests.yml

Add CI for the pre-release PRs = PRs to `bump-meilisearch-v*` during the pre-release week of MeiliSearch. This CI will run the tests against the MeilliSearch RC instead of the MeiliSearch `latest`.
For each PR to `bump-meilisearch-v*`:
- the `linter-check` job will run
- the `integration-tests-against-rc` job will run
- the `integration-tests` job will be skipped
- the required jobs (for merging) in the settings will be: `linter-check` and `integration-tests-against-rc`
For each **push** to `bump-meilisearch-v*`:
- the `linter-check` job will run
- the `integration-tests-against-rc` job will run
- the `integration-tests` job will run
- the required jobs (for merging) in the settings will be: `linter-check` and `integration-tests`
For any other event (PRs and pushes):
- the `linter-check` …

Add pre-release CI

---

src/Client.php
src/Endpoints/Indexes.php
src/Search/SearchResult.php
tests/Endpoints/KeysAndPermissionsTest.php
tests/Endpoints/SearchTest.php
tests/Search/SearchResultTest.php

Hi everyone 👋 
As mentioned here: https://github.com/meilisearch/meilisearch-php/issues/119, here's the `SearchResult` class and the improvements that comes with it. 
There's just a small "DX" way that I'm not sure about: 
- When using `SearchResult::filter()` should the `hits` array be reset to 0 or stay as it? 
IMO, the array could stays as it as we return a new `SearchResult` object but sometimes, it could be good idea to reset the keys from 0 (loops, etc) 🤔 
Thanks for the feedback and have a great day 🙂

Indexes::search() improvements

---

.code-samples.meilisearch.yaml
README.md
src/Delegates/HandlesIndex.php
src/Endpoints/Indexes.php
src/Search/SearchResult.php
tests/Endpoints/ClientTest.php
tests/Endpoints/DocumentsTest.php
tests/Endpoints/IndexTest.php
tests/Endpoints/KeysAndPermissionsTest.php
tests/Endpoints/SearchTest.php

Related to https://github.com/meilisearch/integration-guides/issues/48
Changes:
- New method `$client->index($uid)`: replaces `$client->getIndex($uid)`. Does not do any HTTP call but only returns an `Index` instance.
- New attribute in the `Index` class: `primaryKey`
- New method `$index->fetchRawInfo()`: returns an array of index
- New method `$index->fetchInfo()`: returns an `Index` instance
Breaking changes:
- `$client->getIndex($uid)` now does an HTTP call. Use `$client->index($uid)` instead.
- `$client->updateIndex` returns an `Index` instance.
- `$index->getPrimaryKey()` does not do any HTTP call, but only return the `primaryKey` attribute. Use `$index->fetchPrimaryKey()` if you want the same behavior as the old `$index->getPrimaryKey()`
- `$index->show()` is removed and replaced by …

 Changes due to the implicit index creation

---

.code-samples.meilisearch.yaml
README.md
src/Endpoints/Indexes.php
src/Search/SearchResult.php
tests/Endpoints/SearchTest.php
tests/Search/SearchResultTest.php

- rename `toJson` into `toJSON`: same naming as Stripe and Twilio
- add `rawSearch()` method
- `transformHits` callback can take any callback to completely transform the hits
- Add `transformFacetsDistribution` option in `search()` method (type: callback)
- Add `removeZeroFacets` option in `search()` method (type: boolean)
- Add `transformHits()`, `transformFacetsDistribution()` and `removeZeroFacets()` methods.
```php
$searchResult = $index->search('prince');
$searchResult->removeZeroFacets()
// OR
$searchResult = $index->search('prince', [], ['removeZeroFacets' => true]);
```
```php
$keepAmericanSniperFunc = function (array $hits) {
return array_filter(
$hits,
function (array $hit) { return 'American Sniper' === $hit['title']; }
);
};
$searchResult = $index->search('american'); …
```

Improve the $options parameter in search() method

---

src/Delegates/HandlesIndex.php

I've been seeing the occasional error in my app saying "index already exists". I traced that error back to the "getOrCreateIndex" method.
When the response from meilisearch is empty, it should not try to create the index because we don't know for sure that the index "not found".

Should throw exception if httpBody empty

---

src/Delegates/HandlesIndex.php
src/Endpoints/Indexes.php
src/Exceptions/ApiException.php
src/Http/Client.php
tests/Endpoints/ClientTest.php
tests/Endpoints/DocumentsTest.php
tests/Endpoints/DumpTest.php
tests/Endpoints/IndexTest.php
tests/Endpoints/KeysAndPermissionsTest.php
tests/Endpoints/SearchTest.php
tests/Endpoints/UpdatesTest.php

Rename `MeiliSearch\HTTPRequestException` into `MeiliSearch\ApiException`
Explained here https://github.com/meilisearch/integration-guides/issues/19 and discussed here https://github.com/meilisearch/meilisearch-php/issues/50.  
I hope I understood correctly your intention :smiley:

Rename MeiliSearch\HTTPRequestException into MeiliSearch\ApiException

---

src/Delegates/HandlesSystem.php
tests/Endpoints/ClientTest.php

Checking that method health() return `{'status': 'available'}`  and added isHealthy() method who return boolean value
meilisearch/integration-guides#55

Standardize health method

---

src/Endpoints/Delegates/HandlesSettings.php

These routes receive arrays (as of the documention) as parameters and therefore should enforce the array type to these specific routes.

Add explicit types to parameters

---

.github/workflows/pre-release-tests.yml
.github/workflows/tests.yml
bors.toml
composer.json

Closes #165 
This PR remove the compat with php 7.2. It also uses the most recent version of phpunit to date.
@curquiza In [`MeiliSearch.php`](https://github.com/meilisearch/meilisearch-php/blob/main/src/MeiliSearch.php#L9) the current version is hardcoded. This still needs to be updated when decided which version is next.

Remove php 7.2 support

---

.github/workflows/tests.yml
composer.json
src/Search/SearchResult.php
tests/Endpoints/SearchTest.php

The lint composer command pointed to a non existing config file resulting in the following error: 
`  Cannot read config file "./.php_cs.dist".    `
Path has been updated. 
`composer lint` and `composer lint:fix` are now functional
I changed the scripts used in github actions with the ones from `composer` file.
I'm wondering why it wasn't used before. Am I relying on composer when I shouln't be?

Fix composer lint command

---

src/Exceptions/ApiException.php
src/Http/Client.php
tests/Exceptions/ApiExceptionTest.php

Fixes #171
This PR includes:
- Reworked ApiException constructor, the first argument is now of `ResponseInterface` type
- Fixed all uses of `ApiException`
- Changed `ApiException` tests to use the new constructor
- Added new test that validates that ApiException constructor does not crash with an empty response

Fix ApiException constructor crashing when HTTP body is empty

---

src/Exceptions/FailedJsonEncodingException.php
src/Http/Client.php
tests/Endpoints/DocumentsTest.php

Fix #180 
This PR adds some more tests for properly checking the import of documtens with special characters like they occur in German, French or Russian.
Further it adds a check whether the `json_encode`, that is called to encode the payload sent to MS, fails and throw an exception.

Exception when improper utf8 chars

---

scripts/tests.sh

When launching tests multiple times, I get `Too many open files` error with MeiliSearch. Increase the soft FDs limit reduces this issue.

Increase FD limit to avoid `Too many open files` error

---

src/Endpoints/Delegates/HandlesSettings.php
src/Endpoints/Indexes.php
tests/Settings/SettingsTest.php

This PR is a patch for this [issue](#204).
But it could be interesting to implement a complete JSONSerializer for this SDK see #209.
closed #204.

Fixing issue when send synonyms as empty array

---

src/Http/Client.php

The docblock of the property `$http` in `Http\Client` should be of type `ClientInterface`. This fixes linting on the call to `$this->http->sendRequest()`.

Fix docblock in Http\Client

---

src/Exceptions/InvalidResponseBodyException.php
src/Http/Client.php
tests/Exceptions/InvalidResponseBodyExceptionTest.php
tests/Http/ClientTest.php

Resolves #211 
This implements a new exception `InvalidResponseBodyException` which is thrown when parsing an HTTP response which does not have the Content-Type header `application/json`.
Based on my testing and research, the Meilisearch server will always send `application/json` as the Content-Type except on responses where the status code is `204`. The check is naive and assumes that the Meilisearch server will stick to this convention. If we want the check to be more robust (i.e. case-insensitive, able to handle charset being specified) I can adjust it as necessary.

Check response Content-Type header in HTTP client

---

src/Delegates/HandlesIndex.php
src/Exceptions/ApiException.php
tests/Endpoints/ClientTest.php
tests/Endpoints/IndexTest.php
tests/Exceptions/ApiExceptionTest.php

This not breaking since `errorCode`, `errorType` and `errorLink` in `ApiException` are not renamed into `code`, `type` and `link`.
`$code` is indeed reserved to the main `Exception` class, so I cannot rename `errorCode` into `code` and use it.

Changes related to the new error handler

---

src/MeiliSearch.php

This version is breaking since the current changes in the code base related to the new error handler will make the users of MeiliSaerch v0.23.1 and older to break their code.

Update version for the next release v0.20.0

---

.code-samples.meilisearch.yaml

fixes: #258 
- Add `settings_guide_sortable_1`
- Fix all the `settings_guide` with `udpateSettings()` instead of the sub setting route method.

Update code_sample guide sort 

---

src/Delegates/HandlesIndex.php
tests/Endpoints/ClientTest.php

Removing `delete_if_exist` method.
All the actions on indexes are now asynchronous, the method delete_if_exist is now useless.

Remove delete if exist method

---

.github/workflows/tests.yml

Fixed an error when installing some dependencies with `composer` during CI tests [check here](https://github.com/meilisearch/meilisearch-php/pull/270/checks).

Fixing composer require command

---

src/Exceptions/JsonDecodingException.php
src/Exceptions/JsonEncodingException.php
src/Http/Client.php
src/Http/Serialize/Json.php
src/Http/Serialize/SerializerInterface.php
tests/Endpoints/DocumentsTest.php
tests/Http/ClientTest.php
tests/Http/Serialize/JsonTest.php

This PR is a copy of #270  to check the pipeline.
Applies clean code.
- Rename FailedJsonDecodingException to JsonDecodingException and FailedJsonEncodingException to JsonEncodingException, due to the Exception already making clear that it's a failure.
- Created a unique separated class to be used as JSON encode/decode across the system.
- Standardized the JSON Exception return messages.
Thank you so much for contributing to MeiliSearch!

Extract functionality to a more specific class

---

src/Client.php
src/Delegates/HandlesSystem.php
src/Endpoints/Delegates/HandlesKeys.php
src/Endpoints/Keys.php
tests/Endpoints/IndexTest.php
tests/Endpoints/KeysAndPermissionsTest.php
tests/TestCase.php

Granular management of API keys is now added to MeiliSearch. New methods have been created to manage this:
- `http.patch` use by `updateKey`
- `client.getKey` get information about a specific API key.
- `client.createKey` create a new API key.
- `client.deleteKey` delete an API key.
- `client.updateKey` update an API key.

Addition related to API keys

---

.gitignore

This pull request adds to .gitignore the files generated by the PHPStorm, which is one of the most used PHP IDE.
I was thinking of using the [Gitignore.io](https://www.gitignore.io/) to generate it but I don't know if all those need to be added for this project, [here is the complete list for PHPStorm](https://www.toptal.com/developers/gitignore/api/phpstorm).
If you want, I can recreate the PR with the complete items added to `.gitignore`, just let me know so I can change, otherwise, we can merge with only the `.idea`.
Thank you so much for contributing to MeiliSearch!

add phpstorm folder to gitignore

---

.gitattributes

This is not a fix for any occuring issue but rather an enhancement. Many PHP projects and librarys (e.g. Symfony and Laravel) make use of the .gitattributes file to generate smaller bundles for packagist/composer. When installing the library via composer, the composer command will get the zip archive by default (--prefer-dist) which previously included the `tests` directory and other unnecessary files. With this PR the exported files are `src/`, `composer.json`, `README.md`
You can compare the archive sizes with these links:
[Origin branch ZIP-export](https://github.com/meilisearch/meilisearch-php/archive/refs/heads/main.zip)
[Updated branch ZIP-export](https://github.com/mmachatschek/meilisearch-php/archive/refs/heads/add_git_attributes.zip)
Please check if your PR fulfills the following …

Add .gitattributes file for smaller archive size

---

.github/workflows/pre-release-tests.yml
.github/workflows/tests.yml
bors.toml
composer.json

Fixes #179
This sets the minimum PHP-version to 7.4 which still receives security fixes. PHP 7.3 has [reached its EOL](https://www.php.net/supported-versions.php) in december.

Drop PHP 7.3 support

---

.gitattributes
.gitignore
phpunit.xml.dist
tests/Endpoints/KeysAndPermissionsTest.php
tests/TestCase.php

DX enhancement
This will make it possible to override the default HOST and APIKEY parameter without modifying the base `TestCase` class. If you run multiple instances of meilisearch locally you just need to copy the `phpunit.xml.dist` to `phpunit.xml` and override the appropriate value. `phpunit.xml` is ignored by git. PHPunit will use `phpunit.xml.dist` only if `phpunit.xml` doesn't exist.

Make use of environment variable in PHPUnit

---

src/MeiliSearch.php
tests/VersionTest.php

- Add a function to respond with the full qualified version for the PHP SDK: `"Meilisearch PHP (v0.21.0)"`.
Related to https://github.com/meilisearch/integration-guides/issues/150

Add a func to main class with qualified version

---

src/Contracts/Data.php
src/Contracts/Index/Settings.php
src/Contracts/Index/Synonyms.php
src/Endpoints/Delegates/HandlesSettings.php
src/Endpoints/Indexes.php
tests/Settings/SettingsTest.php
tests/Settings/SynonymsTest.php

This pull request introduces 2 new classes to the Project: Settings and Synonyms.
Both extend from Data, the Data class act as a container to support the other 2 so we can have array access.
Fixes #209
Thank you so much for contributing to MeiliSearch!

Make settings and synonyms be classes so they can be serialized properly

---

src/Endpoints/Delegates/HandlesKeys.php
src/Endpoints/Keys.php
tests/Endpoints/KeysAndPermissionsTest.php

The `class` `Keys` wasn't used as a proper class and did not return objects from the `Keys` but arrays. This has been changed. Setters and Getters have been added to the class.
- `client.getKey` return a Keys
- `client.createKey` return a Keys
- `client.updateKey` return a Keys

Changes the Keys Class

---

tests/Http/ClientTest.php

Check ApiException error code rather than error message to avoid tests break due to Meilisearch API evolving.
Fixes #252 

Modify Client test to check ApiException code rather than ApiException message

---

src/Client.php
src/Contracts/Endpoint.php
src/Delegates/HandlesSystem.php
src/Endpoints/TenantToken.php
src/Exceptions/InvalidArgumentException.php
tests/Endpoints/KeysAndPermissionsTest.php
tests/Endpoints/TenantTokenTest.php
tests/TestCase.php

Introduction of the new method `generateTenantToken`  in order to facilitate the generation of the tenant token.
Related to:
- this issue: https://github.com/meilisearch/meilisearch/issues/1991
- this spec: https://github.com/meilisearch/specifications/pull/89

Adding generateTenantToken method to the client

---

tests/Endpoints/SearchTest.php

As per the changes made in the cropping behavior (now per words see [this spec](https://github.com/meilisearch/specifications/blob/f5c6a8e183e22cc3b80d9a0251c411250f31674f/text/0118-search-api.md#3111-attributestocrop) tests needed to be fixed.

Fix tests due to cropping and facet distribution

---

tests/Endpoints/SearchTestNestedFields.php
tests/TestCase.php

Add tests on nested fields to ensure it is still maintained in Meilisearch.

Ensure nested field support

---

src/Contracts/Index/Settings.php
src/Contracts/Index/TypoTolerance.php
src/Endpoints/Delegates/HandlesSettings.php
tests/Endpoints/IndexTest.php
tests/Search/SearchResultTest.php
tests/Settings/SettingsTest.php
tests/Settings/TypoToleranceTest.php

This PR introduces the new setting: [typoTolerance](https://github.com/meilisearch/specifications/pull/117)
new methods: 
`index.getTypoTolerance()`
`index.updateTypoTolerance(params)`
`index.resetTypoTolerance()`

Add typo tolerance settings

---

src/Endpoints/Keys.php

The `Client::getKeys` method returns the correct number of keys but the same object for all of them.
This was due to the `newInstance` method which returned the instance instead of a new Instance as its name indicated.

Fix `getKeys` method

---

src/MeiliSearch.php

This version makes this package compatible with MeiliSearch v0.27.0🎉 
Check out the changelog of [MeiliSearch v0.27.0](https://github.com/meilisearch/MeiliSearch/releases/tag/v0.27.0) for more information about the changes.
- Add new methods for the new typo tolerance settings #316 @alallema
`index.getTypoTolerance()`
`index.updateTypoTolerance(params)`
`index.resetTypoTolerance()`
- Ensure nested field support #317 @alallema
- Add new search parameters highlightPreTag, highlightPostTag and cropMarker #318 @alallema
* Fix `getKeys` method (#323) @alallema

Update version for the next release (v0.23.2)

---

src/Endpoints/Delegates/HandlesSettings.php
src/Endpoints/Indexes.php

- `PATCH` `/indexes/{indexUid}` instead of `PUT`
- `PATCH` `/indexes/{indexUid}/settings` instead of `POST`
- `PATCH` `/indexes/{indexUid}/settings/typo-tolerance` instead of `POST`
- `PUT` `/indexes/{indexUid}/settings/displayed-attributes` instead of `POST`
- `PUT` `/indexes/{indexUid}/settings/distinct-attribute` instead of `POST`
- `PUT` `/indexes/{indexUid}/settings/filterable-attributes` instead of `POST`
- `PUT` `/indexes/{indexUid}/settings/ranking-rules` instead of `POST`
- `PUT` `/indexes/{indexUid}/settings/searchable-attributes` instead of `POST`
- `PUT` `/indexes/{indexUid}/settings/sortable-attributes` instead of `POST`
- `PUT` `/indexes/{indexUid}/settings/stop-words` instead of `POST`
- `PUT` `/indexes/{indexUid}/settings/synonyms` instead of `POST`

Update HTTP methods

---

.code-samples.meilisearch.yaml
README.md
docker-compose.yml
src/Endpoints/Indexes.php
src/Search/SearchResult.php
tests/Endpoints/SearchTest.php
tests/Endpoints/SearchTestNestedFields.php
tests/Search/SearchResultTest.php

- Rename `nbHits` response parameter to `estimatedTotalHits`.
- Delete `exhaustiveNbHits` response parameter.
- Delete `exhaustiveFacetsCount` response parameter.
- `matches` request parameter is renamed `showMatchesPosition`.
- `_matchesInfo` response parameter is renamed `_matchesPosition`.
- `facetsDistribution` request parameter is renamed `facets`.
- `facetsDistribution` response parameter is renamed `facetDistribution`.
- Rename `transformFacetsDistribution` into `transformFacetDistribution`
- Add a patch to "copy the value" from `estimatedTotalHits` to `nbHits`.

Apply search changes

---

Dockerfile
src/Contracts/Data.php

During the v0.28 implementation, I noticed that I had an annoying warning in the tests, and during the attempts of fixing this warning, I had to move to PHP 7.4 to test, doing that I noticed the Docker config didn't have the `zip` and `git` libraries that are required to composer work.
I probably miss that because the PHP repo saves the vendor stuff locally not in a volume as I was used to, this PR fixes both things!

Add missing docker command + supress warning

---

src/Endpoints/Indexes.php
tests/Endpoints/ClientTest.php
tests/Endpoints/DocumentsTest.php
tests/Endpoints/IndexTest.php
tests/Endpoints/SearchTest.php
tests/Endpoints/TasksTest.php
tests/Endpoints/TenantTokenTest.php
tests/Settings/DisplayedAttributesTest.php
tests/Settings/DistinctAttributeTest.php
tests/Settings/FilterableAttributesTest.php
tests/Settings/RankingRulesTest.php
tests/Settings/SearchableAttributesTest.php
tests/Settings/SettingsTest.php
tests/Settings/SortableAttributesTest.php
tests/Settings/StopWordsTest.php
tests/Settings/SynonymsTest.php
tests/Settings/TypoToleranceTest.php
tests/TestCase.php

This PR changes all the places that currently are handling the summarized task version from `uid` to `taskUid`. And replace the tasks route index namespace with the global one + add the ability to infer the index from it.
disclaimer: The work in the tasks is not done yet, this is the first step.

Tasks refactor v1

---

src/Contracts/IndexesQuery.php
src/Contracts/IndexesResults.php
src/Delegates/HandlesIndex.php
src/Endpoints/Indexes.php
tests/Contracts/IndexesQueryTest.php
tests/Endpoints/ClientTest.php

- Create `IndexesQuery` and `IndexesResults` to handle indexes endpoint
- Apply pagination `IndexesQuery` to indexes endpoint

Indexes v2

---

src/Contracts/DocumentsQuery.php
src/Contracts/DocumentsResults.php
src/Endpoints/Delegates/HandlesDocuments.php
tests/Contracts/DocumentsQueryTest.php
tests/Endpoints/DocumentsTest.php

- Create `DocumentsQuery` to handle pagination in documents endpoint.
- Introduce `DocumentsResults` & make the `getDocuments` return a object
- Add `DocumentsQuery/Results` to `getDocuments` handler

Documents changes v2

---

src/Contracts/KeysQuery.php
src/Contracts/KeysResults.php
src/Endpoints/Delegates/HandlesKeys.php
src/Endpoints/Keys.php
tests/Contracts/KeysQueryTest.php
tests/Endpoints/KeysAndPermissionsTest.php

- Create `KeysQuery` and `KeysResults` to handle pagination in keys endpoint.
- Apply the `KeysQuery` to `getKeys` function
- Rename `$key` to `$keyOrUid` in `getKeys`

Keys changes v2

---

src/MeiliSearch.php

This version makes this package compatible with Meilisearch v0.28.0 :tada:
Check out the changelog of [Meilisearch v0.28.0](https://github.com/meilisearch/meilisearch/releases/tag/v0.28.0) for more information on the changes.
:warning: Small disclaimer: The `rawSearch` (and other `raw*` functions) are a direct connection between your PHP application and Meilisearch, you may find changes that are not present in this section.
- `MeiliSearch\Client->getDumpStatus` method was removed. (#336) @brunoocasali
- `MeiliSearch\Client->getIndexes` method now return a object type `IndexesResults`. (#341), (#345) @brunoocasali
- `MeiliSearch\Client->generateTenantToken` now require a `String apiKeyUid` which is the `uid` of the `Key` instance used to sign the token.  (#343) @brunoocasali
- …

Update version for the next release (v0.24.0)

---

.code-samples.meilisearch.yaml

Fix an issue pointed initially here https://github.com/meilisearch/meilisearch-php/issues/353

Use the correct notation for getting documents

---

src/Endpoints/Delegates/HandlesSettings.php
tests/Endpoints/IndexTest.php

This PR builds upon the PR https://github.com/meilisearch/meilisearch-php/pull/361 from @eelcol to fix CS and allow for merging.
Fixes https://github.com/meilisearch/meilisearch-php/issues/355, https://github.com/meilisearch/meilisearch-php/issues/354 and https://github.com/meilisearch/meilisearch-php/pull/361
Replace https://github.com/meilisearch/meilisearch-php/pull/361

Add faceting and pagination settings

---

.github/workflows/pre-release-tests.yml

I noticed we have only in the pre-release tests (GitHub action config file) some conditionals.
We do not need to add those since we already run without them in the ordinary tests action.

Remove conditionals between steps in pre-release-tests.yml

---

src/Client.php
src/Http/Client.php
tests/Http/ClientTest.php

This PR adds the possibility to inject `StreamFactoryInterface` to not rely on `php-http/discovery`.
The change is done in a way that does not break existing usages.

Allow to inject the StreamFactoryInterface explicitly

---

src/Endpoints/Indexes.php
tests/Endpoints/SearchTest.php

This change allow static analysis tools such as PHPStan or Psalm to detect the return type according to the `$options` array.
For downstream consumers also using a static analysis tool it avoids an unnecessary check/assertion to determine the type of the returned value.

Make possible for static analysis tools to detect return type of `Indexes::search`

---

tests/Endpoints/ClientTest.php
tests/Endpoints/DocumentsTest.php
tests/Endpoints/IndexTest.php
tests/Endpoints/KeysAndPermissionsTest.php
tests/Endpoints/SearchTest.php
tests/Endpoints/SearchTestNestedFields.php
tests/Endpoints/TasksTest.php
tests/Endpoints/TenantTokenTest.php
tests/Settings/DisplayedAttributesTest.php
tests/Settings/DistinctAttributeTest.php
tests/Settings/FilterableAttributesTest.php
tests/Settings/RankingRulesTest.php
tests/Settings/SearchableAttributesTest.php
tests/Settings/SettingsTest.php
tests/Settings/SortableAttributesTest.php
tests/Settings/StopWordsTest.php
tests/Settings/SynonymsTest.php
tests/Settings/TypoToleranceTest.php
tests/TestCase.php

Fixes #334 
- Add function to create randomized index names
- The function adds a UUID behind the given index name, if no index name is given it defaults to `index`

Add uuids to index names for randomization

---

src/Contracts/IndexesResults.php

This class has a bad constructor. It's receiving an array instead of an object as a parameter, which is not a good practice, and PHPdoc does not have a good implementation for documenting nested arrays, so for now what we can do is remove the doc-block, and when a better implementation comes in, we updated doc-block as well.
Fixes #397
- It removes the doc-block of the `IndexesResults` constructor fixing #397

Fix phpdoc block of IndexesResults constructor

---

src/Contracts/Http.php
src/Endpoints/Delegates/HandlesDocuments.php
src/Http/Client.php
tests/Endpoints/DocumentsTest.php

Fixes #238
- Implements methods for batch adding of documents in csv and ndjson format
This is using `preg_split` and `implode` to chunk strings by newline. Let me know if there is a better way to do this.
If this is fine I can implement the rest of the methods from the issue.

Implement methods for CSV and Ndjson batch adds

---

src/Contracts/TasksQuery.php
src/Delegates/TasksQueryTrait.php
src/Endpoints/Indexes.php
tests/Contracts/TasksQueryTest.php
tests/Endpoints/IndexTest.php
tests/Endpoints/TasksTest.php

- Added `setUids(array<int>)` filter to match by `Task.uid`.
- Added `setCanceledBy(array<int>)` filter to match by `Task.canceledBy`
- Added `setBeforeEnqueuedAt(\DateTime)` filter to match by `Task.beforeEnqueuedAt`
- Added `setAfterEnqueuedAt(\DateTime)` filter to match by `Task.AfterEnqueuedAt`
- Added `setBeforeStartedAt(\DateTime)` filter to match by `Task.beforeStartedAt`
- Added `setAfterStartedAt(\DateTime)` filter to match by `Task.AfterStartedAt`
- Added `setBeforeFinishedAt(\DateTime)` filter to match by `Task.beforeFinishedAt`
- Added `setAfterFinishedAt(\DateTime)` filter to match by `Task.AfterFinishedAt`
- ⚠️⚠️  Renamed `setUid(array)` to `setIndexUids(array)` filter to match by `Task.indexUid`
- ⚠️⚠️  Renamed `setStatus(array)` to `setStatuses(array<string>)` filter to …

Fix tasks specs with v0.30rc2

---

src/Search/SearchResult.php
tests/Endpoints/SearchTest.php
tests/TestCase.php

Based on https://github.com/meilisearch/meilisearch-php/pull/370
Related to https://github.com/meilisearch/meilisearch/discussions/2635
Add support to finite pagination.
Now you can call: 
- `$client.search('batman', [ 'page' => 1, 'hitsPerPage' => 10 ])`
- `$client.search('batman', [ 'hitsPerPage' => 10 ])`
- `$client.search('batman', [ 'page' => 4 ])`
`results = $client.search('batman', [ 'page' => 4 ])`
And get a limited pagination with a fixed number of total hits in the results object `results['totalHits']`.
You can still use the `offset/limit` by calling `$client.search('batman', [ 'limit' => 4, 'offset' => 10 ])`
`SearchResult#hitsCount` can still be used for retrieving the value of the total hits.
When it is a finite pagination, it will use `$response['totalHits']`, or ` …

Add support to finitePagination

---

src/Contracts/CancelTasksQuery.php
src/Endpoints/Delegates/HandlesTasks.php
src/Endpoints/Tasks.php
tests/Contracts/CancelTasksQueryTest.php
tests/Endpoints/TasksTest.php

Allow users to cancel a processing or an enqueued task.
A new method `cancelTasks(CancelTasksQuery $query)`
```php
// CancelTasksQuery methods:
setNext(int $next)
setTypes(array $types)
setStatuses(array $statuses)
setIndexUids(array $indexUids)
setUids(array $uids)
setCanceledBy(array $canceledBy)
setBeforeEnqueuedAt(\DateTime $date)
setAfterEnqueuedAt(\DateTime $date)
setBeforeStartedAt(\DateTime $date)
setAfterStartedAt(\DateTime $date)
setBeforeFinishedAt(\DateTime $date)
setAfterFinishedAt(\DateTime $date)
```

Add `cancelTasks` method

---

src/Delegates/HandlesSystem.php
src/Endpoints/Indexes.php
src/Search/SearchResult.php
tests/Endpoints/IndexTest.php
tests/Endpoints/SearchTest.php
tests/TestCase.php

Add a new method in the Client `client->swapIndexes(array $indexes)` to swap indexes. The array should follow this structure: `[['indexA', 'indexB'], ['indexC', 'indexD'], ...]`

Add `swapIndexes` method

---

src/Contracts/DeleteTasksQuery.php
src/Endpoints/Delegates/HandlesTasks.php
src/Endpoints/Tasks.php
tests/Contracts/DeleteTasksQueryTest.php
tests/Endpoints/IndexTest.php

Allow users to delete processed, failed and canceled tasks.
A new method `deleteTasks(DeleteTasksQuery $query)`
```php
// DeleteTasksQuery methods:
setNext(int $next)
setTypes(array $types)
setStatuses(array $statuses)
setIndexUids(array $indexUids)
setUids(array $uids)
setCanceledBy(array $canceledBy)
setBeforeEnqueuedAt(\DateTime $date)
setAfterEnqueuedAt(\DateTime $date)
setBeforeStartedAt(\DateTime $date)
setAfterStartedAt(\DateTime $date)
setBeforeFinishedAt(\DateTime $date)
setAfterFinishedAt(\DateTime $date)
```

Add `deleteTasks` method

---

src/Meilisearch.php

Release a new version to mark the latest changes as **breaking**.
The previous release `v0.26.1` will be deprecated in the packagist.
Related information can be verified here https://github.com/meilisearch/meilisearch-php/pull/441, https://github.com/meilisearch/meilisearch-php/pull/431

Update the version for the next release (v0.27.0)

---

src/Endpoints/Indexes.php
tests/Endpoints/IndexTest.php

- Replace the `string` type by `?DateTime` in `Endpoints\Indexes::createdAt` and `Endpoints\Indexes::updatedAt`

Make createdAt and updatedAt DateTime types not string

---

src/Contracts/CancelTasksQuery.php
src/Contracts/DeleteTasksQuery.php
src/Contracts/TasksQuery.php
src/Delegates/HandlesIndex.php
src/Delegates/TasksQueryTrait.php
tests/Contracts/CancelTasksQueryTest.php
tests/Contracts/DeleteTasksQueryTest.php
tests/Contracts/TasksQueryTest.php
tests/Endpoints/ClientTest.php
tests/Http/ClientTest.php
tests/TestCase.php

- Add `canceledBy` and remove `next` from toArray in `TasksQuery`
- Correct `DeleteTasksQuery` allowed attributes: removed `next`.
- Correct `CancelTasksQuery` allowed attributes: removed `next` and `canceledBy`.
- Correct `TasksQuery` allowed attributes: removed `next`. 
- Remove non-generic methods from `TasksQueryTrait` 
- Remove `deleteAllIndexes`, `getAllRawIndexes`.
- Rename `getAllIndexes` to `getIndexes`.
- Refactor `tearDown` after removing `deleteAllIndexes`

Remove raw methods & Fix query classes

---

src/Meilisearch.php

This version makes this package compatible with Meilisearch v1.0.0 :tada:
Check out the changelog of [Meilisearch v1.0.0](https://github.com/meilisearch/meilisearch/releases/tag/v1.0.0) for more information on the changes.
- `Endpoints/Indexes` date attributes `$createdAt` and `$updatedAt` are `DateTime` now instead of `string`.
- Removed `getCreatedAtString` and `getUpdatedAtString` functions.
- Add `canceledBy`/`setCanceledBy` in `TasksQuery`
- Remove `next` attribute and `setNext` from `TasksQuery`.
- Remove `next` attribute and `setNext` from `DeleteTasksQuery`.
- Remove `next`, `canceledBy` attributes and `setNext`, `setCanceledBy` from `CancelTasksQuery`.
- Remove `deleteAllIndexes`, since they don't really delete all the indexes but only the first page.
- Remove `getAllRawIndexes` …

Update the version for the next release (v1.0.0)

---

src/Endpoints/Delegates/HandlesDocuments.php
tests/Endpoints/DocumentsTest.php
tests/datasets/songs-custom-separator.csv

- Add `?string $delimiter` to `updateDocumentsCsv`, `addDocumentsCsv` and also `addDocumentsCsvInBatches` and `updateDocumentsCsvInBatches`.

Add CSV delimiter to csv document handler methods

---

composer.json
src/Client.php
src/Contracts/SearchQuery.php
src/Endpoints/Delegates/HandlesMultiSearch.php
tests/Contracts/CancelTasksQueryTest.php
tests/Contracts/DeleteTasksQueryTest.php
tests/Contracts/DocumentsQueryTest.php
tests/Contracts/IndexesQueryTest.php
tests/Contracts/KeysQueryTest.php
tests/Contracts/TasksQueryTest.php
tests/Endpoints/MultiSearchTest.php
tests/Endpoints/TasksTest.php

- Add a new class `SearchQuery` which will handle future search requests
- Add a new method in `$client` called `multiSearch()` which will take an array of `SearchQuery`.

Add `multiSearch`

---

tests/Endpoints/TenantTokenTest.php

Just use a wildcard somewhere to ensure the suite will still work after it.

Use wildcards in tests

---

.github/workflows/tests.yml
Dockerfile
README.md
composer.json

Just update one broken link and one old link that still works.
Fix #497 
Note for reviewers:
I had some issues giving an update on one of our peer dependencies, so I took some time to improve the code and also fix the problem.
- Updated PHP version in the linter jobs
- "Force" the usage of the Guzzle 7 in the PHP 8 matrixes 
- Create a new test with Guzzle 6 and PHP 7.4

Update docs links

---

.github/workflows/pre-release-tests.yml
tests/Endpoints/DocumentsTest.php

Fix PHP HTTP libraries deprecations in the Pre-release CI structure.
Also, for some reason, only the `kriswallsmith/buzz` was breaking because of the way I set up the `ResponseInterface` mock.

Bump meilisearch v1.2.0 try pre release rc ci

---

.github/workflows/pre-release-tests.yml
src/Contracts/DocumentsQuery.php
src/Endpoints/Delegates/HandlesDocuments.php
tests/Endpoints/DocumentsTest.php

Introduces a new method, `setFilter` to `DocumentsQuery`, which will add the ability to `getDocuments` to find the documents easily without using the `search` method. 
⚠️ If you want to use the new feature, ensure you're using Meilisearch v1.2.0 or newer.

Add get documents

---

.code-samples.meilisearch.yaml

Hey @brunoocasali, Joaco from the basement team here, found this duplicated key while building meilisearch.com so thought of opening a PR 😁 
- Removes duplicated key `get_documents_1` since it was causing errors on the docs deployment. Removed second examples since it seemed the first one was more useful, but correct me if I'm wrong.
EDIT: The other `get_documents_1` is in line 15.

[FIX]: Remove duplicated key on code-samples

---

src/Contracts/DocumentsQuery.php
tests/Endpoints/DocumentsTest.php

Fixes #522 
Fixed behavior for fields if new documents/fetch endpoint used.

Ppunk documents fetch fix #

---

src/Contracts/SearchQuery.php
tests/Endpoints/MultiSearchTest.php
tests/Endpoints/SearchTest.php

This feature aims to return ranking details for each document to understand and tweak the score of the documents more efficiently.
Ensure the SDKs can handle the new search parameter `showRankingScore`. Also, ensure the SDK can handle the `_rankingScore` attribute in the matched `hits`.

Add support to `showRankingScore`

---

src/Contracts/SearchQuery.php
tests/Endpoints/MultiSearchTest.php
tests/Endpoints/SearchTest.php

This feature aims to return ranking details for each document to understand and tweak the score of the documents more easily.
Ensure the SDKs can handle the new search parameter `showRankingScoreDetails`. Also ensure the SDK can handle the `_rankingScoreDetails` attributes in the matched `hits`.
:warning: This feature is enabled by querying `PATCH /experimental-features` with `{ "scoreDetails": true }`

Feature/Add `showRankingScoreDetails`

---

.github/workflows/docs.yml
.gitignore
.phpdoc/template/base.html.twig
CNAME
README.md

This PR aims at migrating the generated phpDocumentor docs to `php-sdk-docs.meilisearch.com` instead of Github Pages.
(Please ignore the Vercel preview below. It's not relevant anymore.)
This PR:
- Adds the Fathom Analytics script to the generated HTML
- Update the title of the generated docs

Migrate docs hosting to Meilisearch subdomain

---

src/Endpoints/Delegates/HandlesSettings.php
tests/Endpoints/IndexTest.php
tests/Settings/WordDictionaryTest.php

Fixes #569 
- Add dictionary settings
- Create tests

[v1.4] Add word dictionary settings

---

.code-samples.meilisearch.yaml

I created [scripts to manage code samples](https://github.com/meilisearch/integration-automations/pull/164) (internal only)
I found out the following code samples are still in this repo but not used by the documentation anymore:
```bash
meilisearch-php
- 'documents_guide_add_movie_1' not found in documentation
- 'getting_started_communicating_with_a_protected_instance' not found in documentation
- 'faceted_search_facets_1' not found in documentation
- 'faceted_search_2' not found in documentation
```
I checked with another script: no code samples are missing on PHP side for the documentation

Remove useless code samples (not used by the docs anymore)

---

.github/workflows/docs.yml

The documentation deployment is falling:
```
In Application.php line 725:
[Symfony\Component\Console\Exception\CommandNotFoundException]  
Command "tests/" is not defined.                                
Exception trace:
at /opt/phpdoc/vendor/symfony/console/Application.php:725
Symfony\Component\Console\Application->find() at /opt/phpdoc/vendor/symfony/console/Application.php:262
Symfony\Component\Console\Application->doRun() at /opt/phpdoc/src/phpDocumentor/Console/Application.php:78
phpDocumentor\Console\Application->doRun() at /opt/phpdoc/vendor/symfony/console/Application.php:174
Symfony\Component\Console\Application->run() at /opt/phpdoc/bin/phpdoc:14
Error: Process completed with exit code 1.
```
[See the full logs](https://github.com/meilisearch/meilisearch-php/actions/runs/60459089 …

Fix failing documentation deployement

---

src/Http/Client.php
tests/Http/ClientTest.php

Fixes #584
- Fix the issue by also checking if the provided masterkey is an empty string

Fix passing empty masterkey

---

.code-samples.meilisearch.yaml
src/Endpoints/Delegates/HandlesSettings.php
tests/Settings/ProximityPrecisionTest.php

Add `proximityPrecision` management methods

---

src/Contracts/Index/Embedders.php
src/Contracts/Index/Settings.php
src/Endpoints/Delegates/HandlesSettings.php
tests/Endpoints/SearchTest.php
tests/Settings/EmbeddersTest.php
tests/Settings/SettingsTest.php

Adds hybrid search to PHP SDK. 
There is a commented test that should be reverted as soon as the related issue is fixed on the engine.

Add hybrid search for v1.6.0

---

src/Endpoints/Delegates/HandlesSettings.php

Fixes https://github.com/meilisearch/meilisearch-php/pull/606#discussion_r1451919885
- Declares proper typehint to know what values may be returned/accepted.

Use proper typehint for proximityPrecision

---

tests/Endpoints/DocumentsTest.php

- in the old implementation `willReturnCallback()` wasn't called due to `willReturn()` in the end. I removed `willReturn()` and fixed the test.

Fix "CsvInBatchesWithDelimiter"  test

---

.github/workflows/tests.yml
README.md
phpunit.xml.dist
scripts/tests.sh

Fixes #567
- Integrates CodeCov as I did at https://github.com/meilisearch/meilisearch-symfony/pull/322

Added CodeCov coverage report support

---

.code-samples.meilisearch.yaml

Fixes [issue first reported on the documentation repo](https://github.com/meilisearch/documentation/issues/2782).
Add missing `$` to documentation code sample

Add missing `$` to documentation code sample

---

src/Endpoints/Delegates/HandlesSettings.php
tests/Settings/SearchCutoffMsTest.php

Fixes #630
- Add three new methods according to the issue `updateSearchCutoffMs`, `getSearchCutoffMs` and `resetSearchCutoffMs`.

Add `searchCutoffMs` method

---

src/Contracts/SearchQuery.php
src/Contracts/SimilarDocumentsQuery.php
src/Endpoints/Indexes.php
src/Search/SimilarDocumentsSearchResult.php
tests/Endpoints/SimilarDocumentsTest.php
tests/TestCase.php

Fixes #642 
- Add get similar document method

Add get similar document method

---

docker-compose.yml
src/Contracts/DocumentsQuery.php
src/Contracts/SimilarDocumentsQuery.php
tests/Endpoints/DocumentsTest.php
tests/Endpoints/SearchTest.php
tests/Endpoints/SimilarDocumentsTest.php

Fixes #647
- Add setRetrieveVectors method to SimilarDocumentsQuery
- Add setRetrieveVectors method to DocumentsQuery
- Enhance vector tests

V1.9 hybrid search

---

.github/workflows/tests.yml
.php-cs-fixer.dist.php
bors.toml
composer.json

Fixes #619
- Enables parallel config in cs fixer;
- Uses cs fixer shim to avoid conflicts between dependencies;
- Splits CI tests jobs with matrix to run in parallel for faster feedback;
- Uses `ramsey/composer-install` in CI to allow caching dependencies;

Maintenance CI and code base

---

composer.json

Fixes #652
- Removes unneeded `php-http/httplug` and `php-http/client-common` dependencies. This PR is based on #651 to see if it really doesn't break anything. So #651 should be merged before this and after that I'll rebase this PR.

Remove unneeded deps

---

src/Contracts/SearchQuery.php
src/Endpoints/Delegates/HandlesSettings.php
tests/Endpoints/SearchTest.php
tests/Settings/LocalizedAttributesTest.php

> [!WARNING]  
> The tests won't work since the Meilisearch implementation is broken currently in rc0, see the following PR https://github.com/meilisearch/meilisearch/pull/4836
> I did the test on the branch that implemented the change though.
Fixes https://github.com/meilisearch/meilisearch-php/issues/660

Implements localized attributes

---

src/Contracts/FederationOptions.php
src/Contracts/MultiSearchFederation.php
src/Contracts/SearchQuery.php
src/Endpoints/Delegates/HandlesMultiSearch.php
tests/Endpoints/MultiSearchTest.php

Fixes https://github.com/meilisearch/meilisearch-php/issues/659
- Create a new object, `federationOptions`, which can specify the weight of a query.
- Add a method to provide the federationOptions to a search request
- Adds the `federation` field parameter in the multi-search
- Add a test
Hey @norkunas, since you reviewed https://github.com/meilisearch/meilisearch-php/pull/662 and are definitely better than me in PHP I added you as a reviewer in this PR as well.
If you don't have the time don't worry we'll find another reviewer 👍

Handle the new federation options

---

src/Endpoints/Delegates/HandlesDocuments.php
tests/Endpoints/DocumentsTest.php

Fixes https://github.com/meilisearch/meilisearch-php/issues/661
- Implements the update documents by function method
- Add a test

Implements the update documents by function

---

.github/workflows/meilisearch-beta-tests.yml
.github/workflows/pre-release-tests.yml
.github/workflows/tests.yml

Add missing strategy to CI

---

src/Contracts/HybridSearchOptions.php
src/Contracts/SearchQuery.php

Fixes #676
Adds hybrid search options contract for multisearch

feat: Adds hybrid search options contract for multisearch

---

src/Http/Client.php
tests/Http/ClientTest.php
tests/TestCase.php

- Rewinds the PSR-7 StreamInterface
When reading a PSR-7 StreamInterface with getContents() the stream is not automatically rewound. If you for example attach a middleware in Guzzle that reads the StreamInterface but does not rewind it afterwards any calls afterwards will read from the end of the stream resulting in an empty string.
However, then casting the StreamInterface to a string using __toString() then the stream MUST attempt to seek to the beginning of the stream. See https://www.php-fig.org/psr/psr-7/#34-psrhttpmessagestreaminterface

Cast body to a string to force rewind of stream

---

src/Contracts/SimilarDocumentsQuery.php
tests/Contracts/SimilarDocumentsQueryTest.php

Add `rankingScoreThreshold` to `SimilarDocumentsQuery`

---

.code-samples.meilisearch.yaml
src/Contracts/SimilarDocumentsQuery.php
tests/Contracts/SimilarDocumentsQueryTest.php
tests/Endpoints/SearchTest.php
tests/Endpoints/SimilarDocumentsTest.php
tests/Settings/EmbeddersTest.php

Fix #682
- Fix broken tests due to the newly mandatory `embedder` field
- Add test for embedder settings
- Change `SimilarDocumentsQuery` struct:
- make the `embedder` field mandatory when constructing the struct
- remove the `setEmbedder` method

Ai powered api changes

---

src/Contracts/MultiSearchFederation.php
tests/Contracts/MultiSearchFederationTest.php
tests/Endpoints/MultiSearchTest.php

Multi search facet distribution

---

.github/workflows/tests.yml
docker-compose.yml

Fixes #690
Pull the `latest` in the CI instead of forcing the v1.11

fix: pull the latest in the CI instead of forcing the v1.11

---

src/Contracts/TasksQuery.php
tests/Contracts/TasksQueryTest.php
tests/Endpoints/TasksTest.php

Add parameter to get tasks in reverse order

---

src/Endpoints/Delegates/HandlesSettings.php
tests/Settings/FacetSearchTest.php
tests/Settings/PrefixSearchTest.php
tests/Settings/SettingsTest.php

Fixes #694 
- Add tests to make sure `getSettings()`, and `updateSettings` allow the new settings
- Add the `getFacetSearch()`, `updateFacetSearch()`, and `resetFacetSearch()` methods
- Add the `getPrefixSearch()`, `updatePrefixSearch()`, and `resetPrefixSearch()` methods
- Add tests

Add `prefixSearch` and `facetSearch` index settings

---

src/Client.php
src/Contracts/BatchesQuery.php
src/Contracts/BatchesResults.php
src/Contracts/TasksQuery.php
src/Endpoints/Batches.php
src/Endpoints/Delegates/HandlesBatches.php
tests/Endpoints/BatchesTest.php
tests/Endpoints/TasksTest.php

Add batches endpoints

---

src/Search/SearchResult.php

Fixes #700 
- Ensures that `SearchResults::hitsCount` is consistent regardless of whether `estimatedTotalHits` is set.

Make `hitsCount` always the number of `hits` (and not `totalHits` value)

---

tests/Endpoints/SearchNestedFieldsTest.php

- The old name of the test is `SearchTestNestedFields` so phpunit ignored it as this test didn't have `*Test` suffix
- After fixing the name the test failed so I fixed the test:)

Fixed SearchNestedFieldsTest test

---

composer.json
src/Http/Client.php
src/Search/SearchResult.php
tests/Endpoints/SearchTest.php

- new version of PHPStan
- fixed errors reported by PHPStan
- fixed a possible case when some properties could be accesses before initialization in SearchResult class

PHPStan 2 + fixed uninitialized properties in SearchResult

---

tests/Endpoints/BatchesTest.php

Fixes #708 
- Update tests to check that `progress` is available in Batch objects

Add batch progress

---

tests/Endpoints/TasksTest.php

Fixes a flaky tests about getting tasks in reverse order

Fix flaky tasks reverse test

---

.github/workflows/release-drafter.yml
.github/workflows/tests.yml
composer.json
src/Endpoints/Delegates/HandlesMultiSearch.php
src/Exceptions/ApiException.php
src/Exceptions/InvalidResponseBodyException.php
src/Exceptions/TimeOutException.php
tests/Endpoints/MultiSearchTest.php

Fixes #685 on v1.x branch
- Backport #757 to v1.x branch

chore: backport federated search fix
